sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  sauce_connect:
    no_ssl_bump_domains: all
env:
  global:
    - NODE_VERSION=0.10
    - SAUCE_USERNAME="kaazing-build"
    - SAUCE_ACCESS_KEY="f350bbbb-376e-4c0e-b7b6-ae78f58f67f2"
  matrix:
    - platform=Linux browser=firefox
    - platform="Windows 7" browser=firefox
    - platform="OS X 10.11" browser=firefox
    - platform=Linux browser=chrome
    - platform="Windows 7" browser=chrome
    - platform="OS X 10.11" browser=chrome
install:
  - nvm install $NODE_VERSION
  - npm install -g grunt-cli
  - npm install
script:
  - grunt sauceTest
