sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  sauce_connect:
    no_ssl_bump_domains: all
env:
  global:
    - NODE_VERSION=0.12
    - SAUCE_USERNAME="kaazing-build"
    - SAUCE_ACCESS_KEY="f350bbbb-376e-4c0e-b7b6-ae78f58f67f2"
  matrix:
    - platform=Linux browser=firefox version=43
    - platform=Linux browser=firefox version=dev
    - platform=Linux browser=chrome version=47
    - platform=Linux browser=chrome version=dev
    - platform="Windows 10" browser=microsoftedge version=20
    - platform="Windows 10" browser="internet explorer" version=11
    - platform="Windows 8" browser="internet explorer" version=10
    - platform="Windows 7" browser="internet explorer" version=9
    - platform="Windows 7" browser="internet explorer" version=8
    - platform="OS X 10.11" browser=safari version=9
    - platform=Linux browser=android version=5.1 device="Android Emulator"
    - platform="OS X 10.10" browser=iphone version=9.2 device="iPad Retina"
install:
  - nvm install $NODE_VERSION
  - npm install -g grunt-cli
  - npm install
script:
  - grunt sauceTest
